// Autogenerated from Pigeon (v4.2.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by CSSmoothHostApi.
NSObject<FlutterMessageCodec> *CSSmoothHostApiGetCodec(void);

@protocol CSSmoothHostApi
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)pointerEventDateTimeDiffTimeStampWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void CSSmoothHostApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<CSSmoothHostApi> *_Nullable api);

NS_ASSUME_NONNULL_END
