// Mocks generated by Mockito 5.3.2 from annotations
// in smooth/test/src/mock_source.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:smooth/src/actor.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [Actor].
///
/// See the documentation for Mockito's code generation for more information.
class MockActor extends _i1.Mock implements _i2.Actor {
  @override
  set diffDateTimeTimePoint(int? _diffDateTimeTimePoint) => super.noSuchMethod(
        Invocation.setter(
          #diffDateTimeTimePoint,
          _diffDateTimeTimePoint,
        ),
        returnValueForMissingStub: null,
      );
  @override
  int get interestVsyncTargetTimeByLastPreemptRender => (super.noSuchMethod(
        Invocation.getter(#interestVsyncTargetTimeByLastPreemptRender),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
  @override
  set interestVsyncTargetTimeByLastPreemptRender(
          int? _interestVsyncTargetTimeByLastPreemptRender) =>
      super.noSuchMethod(
        Invocation.setter(
          #interestVsyncTargetTimeByLastPreemptRender,
          _interestVsyncTargetTimeByLastPreemptRender,
        ),
        returnValueForMissingStub: null,
      );
  @override
  void debugPrintStat() => super.noSuchMethod(
        Invocation.method(
          #debugPrintStat,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void maybePreemptRender() => super.noSuchMethod(
        Invocation.method(
          #maybePreemptRender,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
